#!/usr/bin/env bash
# One-shot installer for the Kingdom 1685 tracker on a VPS.
#   bash deploy/setup.sh
# Runs the preflight, asks a few questions, writes deploy/.env, and starts the
# whole stack (Android emulator + app + Caddy) with docker compose.
set -euo pipefail

cd "$(dirname "$0")/.."          # repo root
HERE="deploy"
ENV_FILE="$HERE/.env"
COMPOSE=(docker compose -f "$HERE/docker-compose.yml")

echo "============================================="
echo " Kingdom 1685 tracker — VPS setup"
echo "============================================="

# ---- prerequisites ----
if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is not installed. Install it first:  curl -fsSL https://get.docker.com | sh"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "The 'docker compose' plugin is missing. Install Docker Compose v2 and retry."
  exit 1
fi

# ---- preflight (bot/emulator capability) ----
echo; echo "Running preflight check…"; echo
RUN_BOT=1
if ! bash "$HERE/preflight.sh"; then :; fi   # preflight prints its own result
echo
read -r -p "Will this host run the Android emulator/bot here? [Y/n] " a
case "${a:-Y}" in [Nn]*) RUN_BOT=0;; esac

# ---- don't clobber an existing config ----
if [ -f "$ENV_FILE" ]; then
  read -r -p "$ENV_FILE already exists. Overwrite it? [y/N] " o
  case "${o:-N}" in [Yy]*) ;; *) echo "Keeping existing $ENV_FILE."; SKIP_ENV=1;; esac
fi

if [ -z "${SKIP_ENV:-}" ]; then
  echo; echo "--- Settings (press Enter to accept defaults) ---"
  read -r -p "Public domain (blank = serve plain HTTP on :80): " DOMAIN
  read -r -p "Admin username [admin]: " ADMIN_USER;  ADMIN_USER="${ADMIN_USER:-admin}"
  while :; do
    read -r -s -p "Admin password: " ADMIN_PASS; echo
    [ -n "$ADMIN_PASS" ] && break || echo "  password can't be empty"
  done
  read -r -p "Kingdom ID [1685]: " KINGDOM; KINGDOM="${KINGDOM:-1685}"

  SECRET="$(openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | xxd -p | tr -d '\n')"
  COOKIE_SECURE=false; [ -n "$DOMAIN" ] && COOKIE_SECURE=true

  {
    echo "# Generated by deploy/setup.sh on $(date -u +%FT%TZ)"
    [ -n "$DOMAIN" ] && echo "SITE_ADDRESS=$DOMAIN"
    echo "ADMIN_USERNAME=$ADMIN_USER"
    echo "ADMIN_PASSWORD=$ADMIN_PASS"
    echo "KINGDOM_ID=$KINGDOM"
    echo "CONTROL_SECRET=$SECRET"
    echo "COOKIE_SECURE=$COOKIE_SECURE"
    [ "$RUN_BOT" = "0" ] && {
      echo "# Bot not running on this host — point ADB at a real device/emulator:"
      echo "# ADB_CONNECT=PHONE_IP:5555"
      echo "# ADB_SERIAL=PHONE_IP:5555"
    }
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "Wrote $ENV_FILE"
fi

# ---- bring up the stack ----
echo; echo "Starting containers…"
if [ "$RUN_BOT" = "0" ]; then
  "${COMPOSE[@]}" up -d app caddy        # skip the local Android container
else
  "${COMPOSE[@]}" up -d
fi

echo; echo "============================================="
echo " Up! "
if grep -q '^SITE_ADDRESS=' "$ENV_FILE" 2>/dev/null; then
  echo "  Website:  https://$(grep '^SITE_ADDRESS=' "$ENV_FILE" | cut -d= -f2)"
else
  echo "  Website:  http://$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
echo "  Control:  <that URL>/control.html  (log in as the admin you set)"
echo
echo "Next: install RoK into the emulator and calibrate — see docs/3-CONNECT-GAME.md"
echo "Logs:  ${COMPOSE[*]} logs -f app"
echo "============================================="
